version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-site-deliver  
      dockerfile: Dockerfile.frontend
    volumes:
      - ./src:/app/src  # Volume pour synchroniser les fichiers de développement
    ports:
      - "8080:80"  # Port pour accéder à l'app frontend
    depends_on:
      - backend  # Démarrer le backend avant le frontend

  backend:
    build:
      context: ./backend-site-deliver 
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"  # Mappe le port 3000 de l'hôte vers le conteneur backend
    environment:
      DB_HOST: mysql  
      DB_USER: root
      DB_PASSWORD: 1234  
      DB_NAME: site-deliver-bdd
    depends_on:
      - mysql

  mysql:
    image: mysql:latest  
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234  
      MYSQL_DATABASE: site-deliver-bdd 
    ports:
      - "3306:3306"                          
    volumes:
      - mysql_data:/var/lib/mysql           # Volume pour persister les données

volumes:
  mysql_data:  # Volume pour persister les données MySQL
