services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: site-deliver-bdd
  backend-express:
    image: backend-express
    environment:
      DB_HOST: mysql
      DB_NAME: site-deliver-bdd
      DB_USER: root
      DB_PASSWORD: 1234
    depends_on:
      - mysql
    ports:
      - "3000:3000"