# Dockerfile pour le backend Express

# Utiliser l'image Node.js
FROM node:18

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances du projet
RUN npm install

# Copier tout le reste du projet
COPY . .

# Exposer le port de l'application (remplace par celui que ton backend utilise)
EXPOSE 3000

# Commande pour démarrer l'application Express
CMD ["npm", "start"]